<html>
<head>
<script type='text/javascript'>

    function foldinout(theid){
    var theid=document.getElementById(theid)
    theid.style.display=(theid.style.display=='block')? 'block' : 'block'
}
  function foldinouts(theids){
     var theids=document.getElementById(theids)
     theids.style.display=(theids.style.display=='block')? 'none' : 'none'
}

</script>
<style type='text/css' title='default' media='all'>@import 'style.css';</style>
<title>absolutebodyworks.com</title>
<style text='text/css'>
div#content {
display:none;
}
</style>
</head>
<body>
<div id='page'>


<?

Function footer()
{
?></div>
</body>
  </html>
  <?
}
?>